apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 2m
  url: https://argoproj.github.io/argo-helm
  # certSecretRef:
  #   name: tls
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
spec:
  interval: 2m
  timeout: 5m
  chart:
    spec:
      chart: argo-cd
      version: '8.1.2'
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: flux-system
      reconcileStrategy: Revision
      interval: 2m
  targetNamespace: argocd
  install:
    createNamespace: true
    timeout: 2m
    remediation:
      retries: 3
  upgrade:
    timeout: 2m
    remediation:
      remediateLastFailure: True
  values:
    crds:
      keep: false